SELECT * from customer;

-- 1. revenue generated by male vs female customers?

SELECT gender, SUM(purchase_amount) AS revenue
FROM customer
GROUP BY gender;

-- 2. customers used a discount but still spent more than the avg purchase amount?

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
AND purchase_amount >=
(SELECT AVG(purchase_amount) 
FROM customer );

-- 3. top 5 products with highest avg review rating?

SELECT item_purchased, ROUND(AVG(review_rating::numeric),2) AS avg_review_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_review_rating DESC
LIMIT 5;

-- 4. avg purchase amt b/w standard and express shipping?

SELECT shipping_type
FROM customer
GROUP BY shipping_type;

SELECT shipping_type, ROUND(AVG(purchase_amount),2)
FROM customer
WHERE shipping_type in ('Standard','Express')
GROUP BY shipping_type ;

SELECT * from customer;

-- 5. Do subscribed cust spend more? find avg spend n total revenue bw sub n non sub customers

SELECT subscription_status ,
COUNT(customer_id),
ROUND(SUM(purchase_amount),2) as revenue,
ROUND(AVG(purchase_amount),2) AS spend
FROM customer
GROUP BY subscription_status
ORDER BY subscription_status,spend;

-- 6.Which 5 products have highest purchase % with discount applied?

SELECT item_purchased,
ROUND(100 * SUM(CASE 
			WHEN discount_applied = 'Yes' THEN 1 
			ELSE 0
			END
			)
			/COUNT(*),2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- 7. Segment cust into new, returning and loyal based on their total no of prev purchases 
-- and show the count of each segment

SELECT * from customer;

WITH customer_type AS (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
END AS customer_segment
FROM customer )

SELECT customer_segment, COUNT(*) AS no_of_customers
FROM customer_type
GROUP BY customer_segment;


-- 8. top 3 products within each category

WITH items AS(
SELECT item_purchased, 
category,
COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC ) AS item_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM items
WHERE item_rank <= 3;


-- 9. customers who are repeat buyers more than 5, are likely to subscribe?

SELECT subscription_status, COUNT(customer_id)
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 10. What is the revenue contribution of each age group?

SELECT age_group, SUM(purchase_amount) as revenue
FROM customer
GROUP BY age_group
ORDER BY revenue DESC;

